<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <?php echo $this->headTitle(' | ryrobbo') . PHP_EOL; ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/assets/favicon.ico" rel="icon" type="image/x-icon">
        <?php
        echo $this->headLink()->prependStylesheet('/assets/css/bootstrap.min.css')
                ->appendStylesheet('/assets/css/admin.css') . PHP_EOL;
        ?>
        <?php echo $this->headScript() . PHP_EOL; ?>
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <header>
            <div class="container">
                <div class="site-header">
                    <div class="row">
                        <div class="col-lg-4 col-md-4">
                            <a href="/" title="Link to home page">
                                <img src="/assets/images/ryrobbo-logo.png" alt="ryrobbo logo" class="logo">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="navigation">
            <div class="container">
                <div class="navbar navbar-default" role="navigation">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li><a href="/admin">Home</a></li>
                                <li><a href="/admin/pages">Pages</a></li>
                                <li><a href="/admin/posts">Posts</a></li>
                                <li><a href="/admin/categories">Categories</a></li>
                            </ul>

                            <ul class="nav navbar-nav navbar-right">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span> Settings <span class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="/admin/posts/cache">Clear Cache</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <main role="main">
                        <?php echo $this->content ?>
                    </main>
                </div>
            </div>
        </div>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-md-5 col-sm-8 footer-info">
                        <p class="copyright">&copy; 2014 Ryan Robinson</p>
                        <p class="disclaimer">If you plan to use any of the content written by myself, please ensure that you reference it appropriately. Also, please don't plagiarise my work!</p>
                    </div>
                    <div class="col-lg-7 col-md-7 col-sm-4">
                        <a href="http://www.twitter.com/ryrobbo"><img src="/assets/images/twitter-icon.png" title="Follow me on Twatter" alt="Twitter icon" class="img-responsive pull-right social-icon"></a>
                    </div>
                </div>
            </div>
        </footer>
        <script src="/assets/js/jquery-1.10.2.min.js"></script>
        <script src="/assets/js/bootstrap.min.js"></script>
        <script src="/assets/js/jquery.cookie.js"></script>
        <script>
            $(document).ready(function() {
                $('.delete').click(function() {
                    if(!confirm('Are you sure you want to delete this record')) {
                        return false;
                    }
                });
            });
        </script>
    </body>
</html>