<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <?php echo $this->headTitle(' | ryrobbo') . PHP_EOL; ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="/assets/favicon.ico" rel="icon" type="image/x-icon">
        <?php
        echo $this->headLink()->prependStylesheet('/assets/css/bootstrap.min.css')
                ->appendStylesheet('/assets/css/admin.css') . PHP_EOL;
        ?>
        <?php echo $this->headScript() . PHP_EOL; ?>
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="login">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-lg-offset-4 col-md-offset-4 login-form">
                    <?php echo $this->content ?>
                </div>
            </div>
        </div>

    </body>
</html>