<?php
$this->headTitle('Pages');
?>
<div class="page">
    <?php if ($this->deleted): ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-success">
                    <span class="glyphicon glyphicon-info-sign"></span> Page deleted successfully
                </div>
            </div>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-lg-12">
            <h1>All Pages <a href="/admin/pages/add" class="btn btn-info pull-right">Create Page</a></h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Title</th>
                            <th>Slug</th>
                            <th>Posted</th>
                            <th>Published</th>
                            <th>On Menu</th>
                            <th>Order</th>
                            <th>&nbsp;</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->pages as $page) { ?>
                            <tr>
                                <td><?php echo $page->name ?></td>
                                <td><?php echo $page->title ?></td>
                                <td><a href="/page/<?php echo $page->slug ?>" target="_blank"><?php echo $page->slug ?></a></td>
                                <td><?php echo $this->dateFormat(new DateTime($page->posted), IntlDateFormatter::LONG, IntlDateFormatter::NONE, 'en_GB') ?></td>
                                <td><?php if ($page->published == 1): ?> <span class="glyphicon glyphicon-ok"></span> <?php else: ?> <span class="glyphicon glyphicon-remove"></span> <?php endif; ?></td>
                                <td><?php if ($page->onmenu == 1): ?> <span class="glyphicon glyphicon-ok"></span> <?php else: ?> <span class="glyphicon glyphicon-remove"></span> <?php endif; ?></td>
                                <td><?php echo $page->order ?></td>
                                <td class="text-right"><a class="btn btn-success" href="/admin/pages/edit/<?php echo $page->id ?>">Edit</a></td>
                                <td class="text-right"><a class="btn btn-danger delete" href="/admin/pages/delete/<?php echo $page->id ?>">Delete</a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>