<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Admin\Controller\PostCategoryController' => __DIR__ . '/src/Admin/Controller/PostCategoryController.php',
  'Admin\Controller\PageController'         => __DIR__ . '/src/Admin/Controller/PageController.php',
  'Admin\Controller\IndexController'        => __DIR__ . '/src/Admin/Controller/IndexController.php',
  'Admin\Controller\PostController'         => __DIR__ . '/src/Admin/Controller/PostController.php',
  'Admin\Controller\CategoryController'     => __DIR__ . '/src/Admin/Controller/CategoryController.php',
  'Admin\Model\Login'                       => __DIR__ . '/src/Admin/Model/Login.php',
  'Admin\Form\CategoryForm'                 => __DIR__ . '/src/Admin/Form/CategoryForm.php',
  'Admin\Form\LoginForm'                    => __DIR__ . '/src/Admin/Form/LoginForm.php',
  'Admin\Form\PostForm'                     => __DIR__ . '/src/Admin/Form/PostForm.php',
  'Admin\Form\PageForm'                     => __DIR__ . '/src/Admin/Form/PageForm.php',
  'Admin\Form\PostCategoryForm'             => __DIR__ . '/src/Admin/Form/PostCategoryForm.php',
  'Admin\Form\LoginFilter'                  => __DIR__ . '/src/Admin/Form/LoginFilter.php',
  'Admin\Service\Factory\LoginTable'        => __DIR__ . '/src/Admin/Service/Factory/LoginTable.php',
  'Admin\Service\Factory\Session'           => __DIR__ . '/src/Admin/Service/Factory/Session.php',
  'Admin\Service\Factory\LoginTableGateway' => __DIR__ . '/src/Admin/Service/Factory/LoginTableGateway.php',
  'Admin\Service\Invokable\AdminSession'    => __DIR__ . '/src/Admin/Service/Invokable/AdminSession.php',
  'Admin\Service\Mapper\Login'              => __DIR__ . '/src/Admin/Service/Mapper/Login.php',
  'Admin\Module'                            => __DIR__ . '/Module.php',
);
