<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'admin/category/add'   => __DIR__ . '/view/admin/category/add.phtml',
    'admin/category/edit'  => __DIR__ . '/view/admin/category/edit.phtml',
    'admin/category/index' => __DIR__ . '/view/admin/category/index.phtml',
    'admin/index/index'    => __DIR__ . '/view/admin/index/index.phtml',
    'admin/index/login'    => __DIR__ . '/view/admin/index/login.phtml',
    'admin/page/add'       => __DIR__ . '/view/admin/page/add.phtml',
    'admin/page/edit'      => __DIR__ . '/view/admin/page/edit.phtml',
    'admin/page/index'     => __DIR__ . '/view/admin/page/index.phtml',
    'admin/post/add'       => __DIR__ . '/view/admin/post/add.phtml',
    'admin/post/edit'      => __DIR__ . '/view/admin/post/edit.phtml',
    'admin/post/index'     => __DIR__ . '/view/admin/post/index.phtml',
    'layout/login'         => __DIR__ . '/view/layout/login.phtml',
    'layout/admin'         => __DIR__ . '/view/layout/admin.phtml',
);
