<?php
$this->headTitle($this->category->category . ' category');
?>
<div class="page">
    <h1>Posts filed under <em>'<?php echo $this->category->category ?>'</em></h1>
    <?php if ($this->posts->count() > 0) { ?>
        <?php foreach ($this->posts as $post) { ?>
            <div class="post-section">
                <div class="row">
                    <div class="col-lg-12">
                        <h2><a href="/post/<?php echo $post->pslug ?>"><?php echo $post->title ?></a>
                            <span class="pull-right">
                                <time datetime="<?php echo date('Y-m-d', strtotime($post->posted)) ?>">
                                    <?php echo date('d F Y', strtotime($post->posted)) ?>
                                </time>
                            </span>
                        </h2>
                        <p><?php echo $post->description ?></p>
                    </div>
                </div>
            </div>
        <?php } ?>
    <?php } else { ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-info">
                    <span class="glyphicon glyphicon-info-sign"></span> No posts were found in this category
                </div>
            </div>
        </div>
    <?php } ?>
</div>