<?php
$this->headTitle('Create Post');

$this->headScript()->prependFile('/assets/js/tinymce/tinymce.min.js')
        ->appendFile('/assets/js/tinymce.config.js');

$form = $this->form;
$form->prepare();
?>
<div class="page">
    <div class="row">
        <div class="col-lg-12">
            <h1>Add Post</h1>
            <form action="/admin/posts/add" method="post" name="postform" id="post-form" class="form">
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('title')) . PHP_EOL; ?>
                    <?php echo $this->formElement($form->get('title')) . PHP_EOL; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('description')) . PHP_EOL; ?>
                    <?php echo $this->formElement($form->get('description')) . PHP_EOL; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('content')) . PHP_EOL; ?>
                    <?php echo $this->formElement($form->get('content')) . PHP_EOL; ?>
                    <?php echo $this->formElement($form->get('id')) . PHP_EOL; ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('published')) . PHP_EOL; ?>
                    <?php echo $this->formElement($form->get('published')) . PHP_EOL; ?>
                </div>
                <button class="btn btn-success btn-lg">Save Post</button>
            </form>
        </div>
    </div>
</div>