<?php
$this->headTitle('Posts');
?>
<div class="page">
    <?php if ($this->cleared): ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-success">
                    <span class="glyphicon glyphicon-info-sign"></span> Cache cleared successfully
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($this->deleted): ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-success">
                    <span class="glyphicon glyphicon-info-sign"></span> Post deleted successfully
                </div>
            </div>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-lg-12">
            <h1>All Posts <a href="/admin/posts/add" class="btn btn-info pull-right">Create Post</a></h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Slug</th>
                            <th>Description</th>
                            <th>Posted</th>
                            <th>Published</th>
                            <th>&nbsp;</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->posts as $post) { ?>
                            <tr>
                                <td><?php echo $post->title ?></td>
                                <td><a href="/post/<?php echo $post->slug ?>" target="_blank"><?php echo $post->slug ?></a></td>
                                <td><?php echo $post->description ?></td>
                                <td><?php echo date('d F Y', strtotime($post->posted)) ?></td>
                                <td><?php if ($post->published == 1): ?> <span class="glyphicon glyphicon-ok"></span> <?php else: ?> <span class="glyphicon glyphicon-remove"></span> <?php endif; ?></td>
                                <td class="text-right"><a class="btn btn-success" href="/admin/posts/edit/<?php echo $post->id ?>">Edit</a></td>
                                <td class="text-right"><a class="btn btn-danger delete" href="/admin/posts/delete/<?php echo $post->id ?>">Delete</a></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>