<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <?php echo $this->headTitle(' | ryrobbo') . PHP_EOL; ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headMeta() . PHP_EOL ?>
        <?php echo $this->headScript() . PHP_EOL ?>
        <link href="/assets/favicon.ico" rel="icon" type="image/x-icon">
        <?php
        echo $this->headLink()->prependStylesheet('/assets/css/bootstrap.min.css')
                ->appendStylesheet('/assets/css/main.css') . PHP_EOL;
        ?>
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <header>
            <div class="container">
                <div class="site-header">
                    <div class="row">
                        <div class="col-lg-4 col-md-4">
                            <a href="/" title="Link to home page">
                                <img src="/assets/images/ryrobbo-logo.png" alt="ryrobbo logo" class="logo">
                            </a>
                        </div>
                        <div class="col-lg-4 col-md-5 col-lg-push-4 col-md-push-3">
                            <nav>
                                <?php echo $this->partial('partial/menu') ?>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8">
                    <main role="main">
                        <?php echo $this->content ?>
                    </main>
                </div>
                <div class="col-lg-3 col-md-3 col-lg-offset-1 col-md-offset-1">
                    <aside>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-6">
                                <div class="sidebar-item">
                                    <?php echo $this->partial('partial/recentposts') ?>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-6">
                                <div class="sidebar-item">
                                    <?php echo $this->partial('partial/categories') ?>
                                </div>
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-md-5 col-sm-8 footer-info">
                        <p class="copyright">&copy; 2014 Ryan Robinson</p>
                        <p class="disclaimer">If you plan to use any of the content written by myself, please ensure that you reference it appropriately. Also, please don't plagiarise my work!</p>
                    </div>
                    <div class="col-lg-7 col-md-7 col-sm-4">
                        <a href="http://www.twitter.com/ryrobbo"><img src="/assets/images/twitter-icon.png" title="Follow me on Twatter" alt="Twitter icon" class="img-responsive pull-right social-icon"></a>
                    </div>
                </div>
            </div>
        </footer>
        <script src="/assets/js/jquery-1.10.2.min.js"></script>
        <script src="/assets/js/bootstrap.min.js"></script>
        <script src="/assets/js/jquery.cookie.js"></script>
        <script>
            (function(i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function() {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-52459282-2', 'auto');
            ga('send', 'pageview');
        </script>
    </body>
</html>