<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'error/404'           => __DIR__ . '/view/error/404.phtml',
    'error/index'         => __DIR__ . '/view/error/index.phtml',
    'layout/layout'       => __DIR__ . '/view/layout/layout.phtml',
    'blog/post/index'     => __DIR__ . '/view/blog/post/index.phtml',
    'blog/page/index'     => __DIR__ . '/view/blog/page/index.phtml',
    'blog/page/contact'   => __DIR__ . '/view/blog/page/contact.phtml',
    'blog/index/index'    => __DIR__ . '/view/blog/index/index.phtml',
    'blog/category/index' => __DIR__ . '/view/blog/category/index.phtml',
    'partial/categories'  => __DIR__ . '/view/partial/categories.phtml',
    'partial/recentposts' => __DIR__ . '/view/partial/recentposts.phtml',
    'partial/menu'        => __DIR__ . '/view/partial/menu.phtml',
);
