<?php
$this->headTitle('Edit Category');

$this->headScript()->prependFile('/assets/js/tinymce/tinymce.min.js')
        ->appendFile('/assets/js/tinymce.config.js');

$form = $this->form;
$form->prepare();
?>
<div class="page">
    <?php if ($this->updated): ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-success">
                    <span class="glyphicon glyphicon-info-sign"></span> Category updated successfully
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($this->insert): ?>
        <div class="row">
            <div class="col-lg-12">
                <div class="alert alert-success">
                    <span class="glyphicon glyphicon-info-sign"></span> Category created successfully
                </div>
            </div>
        </div>
    <?php endif; ?>
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8">
            <h1>Edit Category</h1>
            <?php echo $this->form()->openTag($form) . PHP_EOL; ?>
            <div class="form-group">
                <?php echo $this->formLabel($form->get('category')) . PHP_EOL; ?>
                <?php echo $this->formElement($form->get('category')) . PHP_EOL; ?>
                <?php echo $this->formElement($form->get('id')) . PHP_EOL; ?>
            </div>
            <button class="btn btn-success btn-lg">Save Page</button>
            <?php echo $this->form()->closeTag($form) . PHP_EOL; ?>
        </div>
    </div>
</div>