<?php
$this->headTitle($this->post->title);
$this->headMeta()->setName('description', $this->post->description);

// TWITTER Meta
$this->headMeta()->setName('twitter:card', 'summary_large_image');
$this->headMeta()->setName('twitter:creator', '@ryrobbo');
$this->headMeta()->setName('twitter:title', $this->post->title);
$this->headMeta()->setName('twitter:description', $this->post->description);
$this->headMeta()->setName('twitter:image:src', 'http://ryrobbo.com/assets/images/uploads/' . $this->post->id . '.png');
$this->headMeta()->setName('twitter:site', '@ryrobbo');
$this->headMeta()->setName('twitter:domain', 'http://ryrobbo.com');

// CSS AND JS
$this->headLink(array(
    'rel' => 'author',
    'href' => 'https://plus.google.com/+RyanRobinsonn'
))->appendStylesheet('/assets/css/shCore.css')
        ->appendStylesheet('/assets/css/shThemeDefault.css');

$this->headScript()->appendFile('/assets/js/shCore.js')
        ->appendFile('/assets/js/shAutoloader.js');
?>
<article class="post">
    <hgroup>
        <h1><?php echo $this->post->title; ?></h1>
    </hgroup>
    <p class="post-info">
        <strong>Posted:</strong>
        <time datetime="<?php echo date('Y-m-d', strtotime($this->post->posted)) ?>">
            <?php echo date('d F Y', strtotime($this->post->posted)) ?>
        </time>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <strong>Categories:</strong> <?php echo $this->getPostCategory($this->post->id) ?>
    </p>
    <?php echo $this->post->content ?>
</article>
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'ryrobbo'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script');
        dsq.type = 'text/javascript';
        dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
<script>
    SyntaxHighlighter.autoloader(
            'js /assets/js/shBrushJScript.js',
            'php /assets/js/shBrushPhp.js',
            'css /assets/js/shBrushCss.js',
            'xml /assets/js/shBrushXml.js',
            'sql /assets/js/shBrushSql.js'
            )
    SyntaxHighlighter.all()
</script>